USE ObuvDB;
GO

CREATE TABLE Roles (
	RoleID INT IDENTITY(1,1) PRIMARY KEY,
	RoleName NVARCHAR(50) NOT NULL
);

CREATE TABLE Postavshiki (
	PostID INT IDENTITY(1,1) PRIMARY KEY,
	Nazvanie NVARCHAR(50) NOT NULL
);

CREATE TABLE Proizvoditeli (
	ProizID INT IDENTITY(1,1) PRIMARY KEY,
	Nazvanie NVARCHAR(50) NOT NULL
);

CREATE TABLE Kategorii (
	KatID INT IDENTITY(1,1) PRIMARY KEY,
	Nazvanie NVARCHAR(50) NOT NULL
);

CREATE TABLE Users (
	UserID INT IDENTITY(1,1) PRIMARY KEY,
	RoleID INT NOT NULL,
	FIO NVARCHAR(100) NOT NULL,
	Login NVARCHAR(50) UNIQUE NOT NULL,
	Password NVARCHAR(50) NOT NULL,

	FOREIGN KEY (RoleID) REFERENCES Roles(RoleID) ON DELETE CASCADE
);

CREATE TABLE Tovar (
	Artikul NVARCHAR(50) PRIMARY KEY,
	Naimenovanie NVARCHAR(100) NOT NULL,
	EdIzm NVARCHAR(10) NOT NULL,
	Cena DECIMAL(18,2) NOT NULL,
	PostID INT NOT NULL,
	ProizID INT NOT NULL,
	KatID INT NOT NULL,
	Skidka INT NOT NULL,
	Kolvo INT NOT NULL,
	Opisanie NVARCHAR(MAX) NOT NULL,
	Foto NVARCHAR(255) NULL,

	FOREIGN KEY (PostID) REFERENCES Postavshiki(PostID),
	FOREIGN KEY (ProizID) REFERENCES Proizvoditeli(ProizID),
	FOREIGN KEY (KatID) REFERENCES Kategorii(KatID)
);

CREATE TABLE PunktyVydachi (
	PunktID INT IDENTITY(1,1) PRIMARY KEY,
	Adres NVARCHAR(200) NOT NULL
);

CREATE TABLE Zakaz (
	ZakazID INT IDENTITY(1,1) PRIMARY KEY,
	DataZakaza DATE NOT NULL,
	DataDostavki DATE NOT NULL,
	PunktID INT NOT NULL,
	UserID INT NOT NULL,
	Kod INT NOT NULL,
	Status NVARCHAR(50) NOT NULL,

	FOREIGN KEY (PunktID) REFERENCES PunktyVydachi(PunktID) ON DELETE CASCADE,
	FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE ZakazItems (
	ItemID INT IDENTITY(1,1) PRIMARY KEY,
	ZakazID INT NOT NULL,
	Artikul NVARCHAR(50) NOT NULL,
	Quantity INT NOT NULL,

	FOREIGN KEY (ZakazID) REFERENCES Zakaz(ZakazID) ON DELETE CASCADE,
	FOREIGN KEY (Artikul) REFERENCES Tovar(Artikul) ON DELETE CASCADE
);